import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Store } from '../src/store.js';
import { createPublisher } from '../src/publisher.js';
import { hash, resolve, validateArticle } from '../src/personalize.js';
import { createWP, WPError } from '../src/wordpress.js';
import { searchPosts } from '../src/search.js';

const site=(id='a')=>({id,name:id,url:`https://${id}.example.com`,authorId:7,categoryIds:[12],personalization:{practice_name:`Practice ${id}`,appointment_url:`https://${id}.example.com/book`}});
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'wp-publisher-'));t.after(()=>rm(root,{recursive:true,force:true}));const store=new Store(root);await store.init();const bytes=Buffer.from('test-image'),id=hash(bytes);await writeFile(path.join(root,'assets',id),bytes);await store.write(`assets/${id}.json`,{type:'image/png',extension:'png'});return {store,article:{id:'article-one',title:'Hello {{practice_name}}',content:'<p>{{practice_name}}</p>{{image:photo}}',excerpt:'',featured:'photo',assets:{photo:{assetId:id,alt:'A & B'}}}};}
function mockWP(){const calls=[],media=new Map();let postId=100,mediaId=1;const wp=async(s,endpoint,options={})=>{calls.push({site:s.id,endpoint,options});if(endpoint==='users/me?context=edit')return {id:7,capabilities:{edit_posts:true,upload_files:true}};if(endpoint==='categories/12')return {id:12};if(endpoint==='media'){const id=mediaId++;const m={id,source_url:`${s.url}/uploads/${id}.png`,alt_text:options.body.get('alt_text')};media.set(`${s.id}/${id}`,m);return m;}if(endpoint.startsWith('media/')){const id=Number(endpoint.match(/media\/(\d+)/)[1]),m=media.get(`${s.id}/${id}`);if(!m)throw new Error('Missing media');if(options.method)m.alt_text=JSON.parse(options.body).alt_text;return m;}if(endpoint==='posts'){return {id:postId++,status:'draft',link:`${s.url}/?p=${postId}`};}throw new Error(`Unexpected endpoint ${endpoint}`);};return {wp,calls};}

test('personalization escapes HTML and rejects unresolved/unsafe values',()=>{assert.equal(resolve('{{name}}',{name:'A < B & "C"'},{},true),'A &lt; B &amp; &quot;C&quot;');assert.throws(()=>resolve('{{missing}}',{}),/Missing/);assert.throws(()=>resolve('{{constructor}}',{}),/Missing/);assert.throws(()=>resolve('{{appointment_url}}',{appointment_url:'javascript:alert(1)'}),/HTTPS/);assert.throws(()=>resolve('{{bad',{}),/malformed/);assert.throws(()=>validateArticle({id:'a',title:'a',content:'<img src=x onerror=alert(1)>'}),/active HTML/);assert.throws(()=>validateArticle({id:'a',title:'a',content:'<img src="{{image:x}}">',assets:{x:{assetId:'x'}}}),/between HTML/);});

test('two sites receive their own media URLs; repeat batch creates nothing',async t=>{const {store,article}=await fixture(t);const {wp,calls}=mockWP();const pub=createPublisher(store,wp);const results=await pub.publish(article,[site('a'),site('b')],'run-one');assert.deepEqual(results.map(r=>r.status),['done','done']);const posts=calls.filter(c=>c.endpoint==='posts');assert.equal(posts.length,2);for(const c of posts){const payload=JSON.parse(c.options.body);assert.equal(payload.status,'draft');assert.match(payload.content,new RegExp(`https://${c.site}.example.com/uploads/`));assert.match(payload.content,new RegExp(`Practice ${c.site}`));assert.equal(payload.author,7);assert.deepEqual(payload.categories,[12]);assert.ok(payload.featured_media);}
 const again=await createPublisher(store,wp).publish(article,[site('a'),site('b')],'run-two');assert.deepEqual(again.map(r=>r.status),['skipped','skipped']);assert.equal(calls.filter(c=>c.endpoint==='posts').length,2);assert.equal(calls.filter(c=>c.endpoint==='media').length,2);
});

test('one site failing authentication does not prevent another site',async t=>{const {store,article}=await fixture(t),mock=mockWP();const wp=(s,e,o)=>{if(s.id==='a')throw new Error('Authentication failed');return mock.wp(s,e,o);};const results=await createPublisher(store,wp).publish(article,[site('a'),site('b')],'run');assert.deepEqual(results.map(r=>r.status),['failed','done']);});

test('unknown post outcome blocks repeat creation after restart',async t=>{const {store,article}=await fixture(t),mock=mockWP();let attempts=0;const wp=(s,e,o)=>{if(e==='posts'){attempts++;throw new WPError('Timed out; outcome unknown',true);}return mock.wp(s,e,o);};await createPublisher(store,wp).publish(article,[site()],'one');const result=await createPublisher(store,wp).publish(article,[site()],'two');assert.equal(attempts,1);assert.match(result[0].message,/unknown/);});

test('unknown media outcome blocks reupload after restart',async t=>{const {store,article}=await fixture(t),mock=mockWP();let attempts=0;const wp=(s,e,o)=>{if(e==='media'){attempts++;throw new WPError('Timed out; outcome unknown',true);}return mock.wp(s,e,o);};await createPublisher(store,wp).publish(article,[site()],'one');await createPublisher(store,wp).publish(article,[site()],'two');assert.equal(attempts,1);});

test('definite post rejection reuses uploaded media on retry',async t=>{const {store,article}=await fixture(t),mock=mockWP();let fail=true;const wp=(s,e,o)=>{if(e==='posts'&&fail)throw new WPError('HTTP 403 permission denied');return mock.wp(s,e,o);};await createPublisher(store,wp).publish(article,[site()],'one');fail=false;const result=await createPublisher(store,wp).publish(article,[site()],'two');assert.equal(result[0].status,'done');assert.equal(mock.calls.filter(c=>c.endpoint==='media').length,1);});

test('concurrent batches are rejected',async t=>{const {store,article}=await fixture(t),mock=mockWP();let release;const gate=new Promise(resolve=>release=resolve);const pub=createPublisher(store,async(s,e,o)=>{await gate;return mock.wp(s,e,o);});const first=pub.publish(article,[site()],'one');await assert.rejects(pub.publish(article,[site()],'two'),/already running/);release();await first;});

test('HTTP client redacts error text, forbids redirects, and marks malformed writes unknown',async()=>{process.env.WP_A_USERNAME='user';process.env.WP_A_APP_PASSWORD='secret';let options;const wp=createWP(async(url,o)=>{options=o;return new Response(JSON.stringify({code:'rest_forbidden',message:'echo secret'}),{status:403});});await assert.rejects(wp(site(),'posts',{method:'POST'}),e=>!e.message.includes('secret')&&e.message.includes('403')&&!e.unknown);assert.equal(options.redirect,'error');const malformed=createWP(async()=>new Response('not json'));await assert.rejects(malformed(site(),'media',{method:'POST'}),e=>e.unknown);delete process.env.WP_A_USERNAME;delete process.env.WP_A_APP_PASSWORD;});

test('search uses exact slug, modified dates and isolates failures',async()=>{const calls=[];const results=await searchPosts(async(s,e)=>{calls.push(e);if(s.id==='b')throw new Error('Unavailable');return [{id:2,title:{raw:'Test'},status:'draft'}];},[site('a'),site('b')],{slug:'a-post',dateField:'modified',from:'2026-01-01',to:'2026-01-31'});const query=new URLSearchParams(calls[0].split('?')[1]);assert.equal(query.get('slug'),'a-post');assert.equal(query.get('modified_after'),'2026-01-01T00:00:00');assert.equal(query.get('modified_before'),'2026-01-31T23:59:59');assert.equal(results[0].posts.length,1);assert.equal(results[1].error,'Unavailable');await assert.rejects(searchPosts(async()=>[],[site()],{from:'2026-02-31'}),/Invalid date/);});
